name: Radicale
version: "3.1.5"
slug: radicale
description: "A simple calendar server for Home Assistant"
url: "https://github.com/ollywelch/hassio-radicale"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
image: "ghcr.io/ollywelch/{arch}-hassio-radicale"
ports:
  5232/tcp: 5232
ports_description:
  5232/tcp: "Radicale server port"
options:
  users:
    - username: radicale
      password: radicale
schema:
  users:
    - username: str
      password: str
webui: https://[HOST]:[PORT:5232]